import json
from typing import Iterable, List, Dict

def build_profile(syscalls: Iterable[str]) -> Dict:
    """Devuelve un dict con la política seccomp mínima."""
    return {
        "defaultAction": "SCMP_ACT_ERRNO",
        "archMap": [  # valores por defecto de Docker
            { "architecture": "SCMP_ARCH_X86_64", "subArchitectures": [] }
        ],
        "syscalls": [
            {
                "names": sorted(list(syscalls)),
                "action": "SCMP_ACT_ALLOW",
                "args": [],
                "comment": "Generated by AutoSeccomp-Gen",
                "includes": {},
                "excludes": {}
            }
        ]
    }

def save_profile(profile: Dict, path: str) -> None:
    with open(path, "w") as fh:
        json.dump(profile, fh, indent=2)
